### ISSUE TITLE
Planning of the Convid 19 hand washing mobile app. 

### ISSUE THREAD

**Issue by johnsani** [hngi/fury-mobile#1]
We can continue our discussion here

**Comment by maroafenogho** [comment]
I due time

**Comment by Trojan9** [comment]
https://covid19api.com/   api for covid19

**Comment by fridaychukwuamaka** [comment]
Good one @Trojan9

**Comment by vectaaa** [comment]
OK good morning mobile guys ehm flutter right?
If yes pls proficient flutter devs do drop a message

**Comment by bayodekehinde** [comment]
I am not proficient in flutter ,any other tasks to do

**Comment by maroafenogho** [comment]
Other tasks will come up pretty soon. @damisco87 where are we with the designs?

**Comment by johnsani** [comment]
@Trojan9 I suggest spelling out all the necessary tasks, so that we can all participate. Some people here are lost and don't have an idea on what to do. Thanks

**Comment by damisco87** [comment]
Hi guys, how is everyone today? I am sorry for not being online. My power supply has not been restored since yesterday. My laptop is down since then, I am only responding through my email option as I can only have access through an old iPad that cannot install slack on it. I hope the team lead will post the tasks here so that everyone can participate as that is the essence of this internship. I believe Timothy is working on getting that sorted soon. I have messaged him to contact the designer since I am not online at the moment. I will be with you as soon as my power is restored. Thanks.




-----Original Message-----

**Comment by damisco87** [comment]
Okay, I just figured this out now. I am back online.

**Comment by damisco87** [comment]
Who is online?

**Comment by damisco87** [comment]
Hi guys, yesterday I developed this chart,
![collaboration chart](https://user-images.githubusercontent.com/50450408/84152549-bd6d6e00-aa5c-11ea-86f0-49b548b83b2b.png)
Although at the moment, we only have 9 active members, some are yet to join this repo. I am thinking we should start working on the following

- [ ] Research
- [ ] coding
- [ ] marketing
- [ ] documentation
- [ ] design

- We can have people volunteering to be involved in working on each of that. At the moment, the coding team is made up of Francis and Friday, although they need more hands.

- people working on Research would likely work with the research group of the team fury to know what they need from us and how we can help in order to have the best app for team fury.
- people working on Marketing will do the same with the marketing team.
- We already have Someone working on Documentation, I will chat her up to know what she has done and to get a report from her.
- The design team, would have limited work to do as  the design is almost ready but in case they need to review and perfect the design with the design group of team fury, this will help us
- please, we can be in more than one team. let me have you feedback on this moving forward.

**Comment by maroafenogho** [comment]
I would like to join the coding team. I would also join the marketing team.

**Comment by maroafenogho** [comment]
I want to see if I can come up with something to enable audio notification along with the displayed text.

**Comment by damisco87** [comment]
Good, thanks @maroafenogho 

I will await the response of other team members

**Comment by johnsani** [comment]
Since I'm not proficient in flutter, I will join the research and assist anywhere I'm needed.

**Comment by damisco87** [comment]
Thanks @johnsani

**Comment by damisco87** [comment]
I have posted on the #discussion #stage2 and #introduction channels on Slack that we need developers that are good in Flutter. Hopefully, we get positive responses so they can work with the coding team

**Comment by maroafenogho** [comment]
As for marketing, I have access to a pretty good audience.

**Comment by maroafenogho** [comment]
What is the update on the work manager?

**Comment by johnsani** [comment]
> What is the update on the work manager?

They're yet to update us

**Comment by bayodekehinde** [comment]
I will join research and marketing

**Comment by bayodekehinde** [comment]
Wat do we have to research about please

**Comment by damisco87** [comment]
@bayodekehinde kindly brainstorm with any other person interested.

I can suggest you focus on what will make people to like the app.

Check this
https://hngi7.slack.com/archives/C014JM0UWSZ/p1591714641485700

**Comment by damisco87** [comment]
> > What is the update on the work manager?
> 
> They're yet to update us

About the workmanager, I am confused. I am only working on getting tasks for everyone to be involved. That was what I shared above.

**Comment by damisco87** [comment]
Or I am missing something? Kindly bring me to speed if so. Thanks

**Comment by damisco87** [comment]
The designer is not sure if we would get our design today. Please, let us activate plan B on the UI. @maroafenogho

**Comment by johnsani** [comment]
@maroafenogho what do you need to start the UI design? The earlier we start working on it,the better.

**Comment by Trojan9** [comment]
https://gadgets.ndtv.com/apps/news/covid-19-samsung-releases-app-to-remind-users-to-wash-hands-2213706

**Comment by damisco87** [comment]
imagine, if Samsung could think of that, that means our idea is not a crap

**Comment by damisco87** [comment]
Research team, please work with the main research team of team furry. try and find out what there plan is for the mobile app we are developing. other teams can work with their respective relevant teams as well.

**Comment by johnsani** [comment]
![download](https://user-images.githubusercontent.com/17270438/84168862-d4698b80-aa6f-11ea-8268-dfc9d161f7f2.jpg)
![Uploading download-1.jpg…]()
![Uploading Life-Reminders-screenshot-2017.jpg…]()

**Comment by johnsani** [comment]
![download](https://user-images.githubusercontent.com/17270438/84168862-d4698b80-aa6f-11ea-8268-dfc9d161f7f2.jpg)
![download-1](https://user-images.githubusercontent.com/17270438/84168893-dc293000-aa6f-11ea-8d4f-747470b99b3b.jpg)
![Life-Reminders-screenshot-2017](https://user-images.githubusercontent.com/17270438/84168899-de8b8a00-aa6f-11ea-8bb6-315eaf609c23.jpg)

**Comment by johnsani** [comment]
Noted

**Comment by johnsani** [comment]
We can come up with ideas from the samples above

**Comment by damisco87** [comment]
sure. the lady said she will also share the part they have finished with me today. As soon as I have it, I will get it across.

**Comment by damisco87** [comment]
I hope everyone can be involved now, if you think there is something we are missing, please raise it so we can all be on the same page. Thanks guys.

**Comment by maroafenogho** [comment]
Update!!!
I am currently working on parts of the UI on flutter.
I am going to start with implementing a countdown timer. I will send a demo here soon enough.

**Comment by damisco87** [comment]
Well done. I got a zip file from the designer right now, I will share shortly

**Comment by damisco87** [comment]
[HandWashing Design (1).zip](https://github.com/hngi/fury-mobile/files/4754193/HandWashing.Design.1.zip)
Here it is.

**Comment by damisco87** [comment]
She said it remains just one part which she is working on at the moment

**Comment by damisco87** [comment]
**ANNOUNCEMENT**
We need to give an update of our works tomorrow by 10 am.

This will enable us to know where we are and what we need to do.

Well done everyone.

**Comment by maroafenogho** [comment]
Update!!!
I have a working countdown timer. I want to know is to make it start at a button click or immediately the activity opens. Ideas please...

**Comment by johnsani** [comment]
I think immediately the activity is opened. It starts automatically

**Comment by damisco87** [comment]
I also think immediately the activity opens is good. Good morning.

**Comment by damisco87** [comment]
**### Our Update in less than 15 mins**
Good morning once again everyone.

Our update in less than 15 minutes time. kindly take this order.....

Hi guys.. me and .... are working on ......... and at the moment we have .... ready. by the end of today ....... would have bee done, We are facing ..... challenge (s), we need the help of the team in .....

### Note
If you are the only one working on a task, just mention your name alone.

**Comment by maroafenogho** [comment]
Alright guys. I am done with that. What's left is to make the UI more attractive.

**Comment by maroafenogho** [comment]
What are the other parts we need to work on?

**Comment by maroafenogho** [comment]
@fridaychukwuamaka
When do you think you would be done with the UI?  
Is anyone working on the notification yet?

**Comment by bayodekehinde** [comment]
> Update!!!
> I have a working countdown timer. I want to know is to make it start at a button click or immediately the activity opens. Ideas please...

Immediately the app is opened is cool

**Comment by damisco87** [comment]
Hi guys, I noticed some of us are not active on the mobile thread on Slack. Good evening. The app is almost ready. 

Please, kindly indicate if you are not following the thread on slack

**Comment by damisco87** [comment]
Hello good afternoon and hope we are all fine? If you reading this, and you have not accepted the Github invitation please do. Also, if you have not received the invite, kindly let me know now, this is tied to your promotion to the next stage. Also, if you have done any tasks (including the one shared some days ago) kindly start sharing now, evidence of job done is needed for promotion as well (Mark mentioned this.)

Lastly, is everyone following with the chat on the Slack Mobile thread? if not, let me know. Thanks

**Comment by damisco87** [comment]
Please, we are closing this issue and opening another one 
https://github.com/hngi/fury-mobile/issues/22
Kindly post your update on this new issue
